import { useState } from 'react'
import { Link } from 'react-router-dom'
import {
  ArrowUpRightIcon,
  CheckIcon,
  ChevronDownIcon,
  CopyIcon,
  DatabaseIcon,
  DownloadIcon,
  RefreshCwIcon,
  SearchXIcon,
  SigmaIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
} from 'lucide-react'
import { toast } from 'sonner'

import { AnswerChartView } from '@/components/copilot/answer-chart'
import type { AnswerTone, CopilotAnswer } from '@/components/copilot/engine'
import { EmptyState } from '@/components/common/empty-state'
import { KpiCard } from '@/components/common/kpi-card'
import { StatusBadge, TONE_TEXT_CLASSES } from '@/components/common/status-badge'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import {
  Table,
  TableBody,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { downloadCsv, formatNumber } from '@/lib/format'
import { cn } from '@/lib/utils'

const TONE_VALUE_CLASSES: Record<AnswerTone, string> = {
  default: 'text-foreground',
  positive: TONE_TEXT_CLASSES.positive,
  warning: TONE_TEXT_CLASSES.warning,
  critical: TONE_TEXT_CLASSES.critical,
}

function answerToClipboardText(answer: CopilotAnswer): string {
  const lines: string[] = []
  if (answer.headline) lines.push(`${answer.headlineLabel ?? 'Answer'}: ${answer.headline}`)
  lines.push(answer.narrative)
  if (answer.metrics && answer.metrics.length > 0) {
    lines.push('')
    for (const m of answer.metrics) lines.push(`- ${m.label}: ${m.value}${m.sublabel ? ` (${m.sublabel})` : ''}`)
  }
  if (answer.table) {
    lines.push('')
    lines.push(answer.table.columns.map((c) => c.label).join(' | '))
    for (const row of answer.table.rows) {
      lines.push(answer.table.columns.map((c) => String(row[c.key] ?? '')).join(' | '))
    }
  }
  lines.push('')
  lines.push(`Sources: ${answer.sources.map((s) => `${formatNumber(s.count)} ${s.label.toLowerCase()}`).join(', ')}`)
  lines.push('Generated by KDH One Asset Copilot from authorised internal records.')
  return lines.join('\n')
}

export interface AnswerViewProps {
  answer: CopilotAnswer
  /** Hidden while the narrative is still being revealed. */
  showPayload: boolean
  onFollowUp: (question: string) => void
  onRegenerate: () => void
}

export function AnswerView({ answer, showPayload, onFollowUp, onRegenerate }: AnswerViewProps) {
  const [copied, setCopied] = useState(false)
  const [vote, setVote] = useState<'up' | 'down' | null>(null)
  const [workingOpen, setWorkingOpen] = useState(false)

  const handleCopy = () => {
    const text = answerToClipboardText(answer)
    if (navigator.clipboard?.writeText) {
      void navigator.clipboard.writeText(text)
    }
    setCopied(true)
    window.setTimeout(() => setCopied(false), 1600)
    toast.success('Answer copied', { description: 'Headline, narrative, metrics and citations copied to the clipboard.' })
  }

  const handleExport = () => {
    if (!answer.table) return
    const rows = answer.table.rows.map((row) => {
      const out: Record<string, unknown> = {}
      for (const col of answer.table!.columns) out[col.label] = row[col.key] ?? ''
      return out
    })
    downloadCsv(answer.table.csvName, rows)
    toast.success('Exported to CSV', { description: `${rows.length} rows written to ${answer.table.csvName}.csv` })
  }

  const handleVote = (next: 'up' | 'down') => {
    setVote(next)
    if (next === 'up') {
      toast.success('Thanks — feedback recorded', { description: 'Positive rating logged against this answer for model tuning.' })
    } else {
      toast('Feedback recorded', { description: 'Flagged for review by the KDH data governance team.' })
    }
  }

  if (!showPayload) return null

  return (
    <div className="mt-4 space-y-4">
      {/* Headline */}
      {answer.headline && (
        <div className="rounded-xl border border-border bg-muted/40 px-4 py-3.5">
          <p className="text-xs font-medium tracking-wide text-muted-foreground uppercase">
            {answer.headlineLabel ?? 'Answer'}
          </p>
          <p
            className={cn(
              'mt-1 text-3xl leading-none font-semibold tracking-tight',
              TONE_VALUE_CLASSES[answer.headlineTone ?? 'default'],
            )}
          >
            {answer.headline}
          </p>
        </div>
      )}

      {/* Metric tiles */}
      {answer.metrics && answer.metrics.length > 0 && (
        <div className="grid grid-cols-2 gap-2.5 lg:grid-cols-4">
          {answer.metrics.map((m) => (
            <KpiCard
              key={m.label}
              label={m.label}
              value={m.value}
              sublabel={m.sublabel}
              intent={m.tone ?? 'default'}
              className="p-3"
            />
          ))}
        </div>
      )}

      {/* Chart */}
      {answer.chart && (
        <div className="rounded-xl border border-border bg-card p-3">
          {answer.chart.title && (
            <p className="mb-2 px-1 text-xs font-medium text-muted-foreground">{answer.chart.title}</p>
          )}
          <AnswerChartView chart={answer.chart} />
        </div>
      )}

      {/* Facts (profile / status mix) */}
      {answer.facts && answer.facts.length > 0 && (
        <dl className="grid grid-cols-1 gap-x-6 gap-y-1.5 rounded-xl border border-border bg-card px-4 py-3 sm:grid-cols-2">
          {answer.facts.map((f) => (
            <div key={f.label} className="flex items-baseline justify-between gap-3 border-b border-border/50 py-1 last:border-0">
              <dt className="shrink-0 text-xs text-muted-foreground">{f.label}</dt>
              <dd className={cn('min-w-0 truncate text-right text-xs font-medium text-foreground', f.mono && 'font-mono')}>
                {f.badge ? <StatusBadge status={f.value} /> : f.value}
              </dd>
            </div>
          ))}
        </dl>
      )}

      {/* No rows matched */}
      {answer.table && answer.table.rows.length === 0 && (
        <EmptyState
          icon={SearchXIcon}
          title="No records matched this filter"
          description="The query ran successfully against the authorised records — there is simply nothing in this window. Widen the period or remove a filter."
          action={
            answer.table.link ? (
              <Button asChild variant="outline" size="sm">
                <Link to={answer.table.link.to}>{answer.table.link.label}</Link>
              </Button>
            ) : undefined
          }
        />
      )}

      {/* Table */}
      {answer.table && answer.table.rows.length > 0 && (
        <div className="overflow-hidden rounded-xl border border-border bg-card">
          <div className="[&_[data-slot=table-container]]:max-h-[380px]">
            <Table>
              <TableHeader className="[&_th]:sticky [&_th]:top-0 [&_th]:z-10 [&_th]:bg-card">
                <TableRow>
                  {answer.table.columns.map((c) => (
                    <TableHead key={c.key} className={cn('whitespace-nowrap', c.align === 'right' && 'text-right')}>
                      {c.label}
                    </TableHead>
                  ))}
                </TableRow>
              </TableHeader>
              <TableBody>
                {answer.table.rows.map((row, i) => (
                  <TableRow key={i}>
                    {answer.table!.columns.map((c) => (
                      <TableCell
                        key={c.key}
                        className={cn(
                          'whitespace-nowrap',
                          c.align === 'right' && 'text-right tabular-nums',
                          c.mono && 'font-mono text-xs',
                        )}
                      >
                        {c.badge && row[c.key] ? <StatusBadge status={String(row[c.key])} /> : row[c.key]}
                      </TableCell>
                    ))}
                  </TableRow>
                ))}
              </TableBody>
              {answer.table.totalRow && (
                <TableFooter className="[&_td]:sticky [&_td]:bottom-0 [&_td]:z-10 [&_td]:bg-muted">
                  <TableRow>
                    {answer.table.columns.map((c) => (
                      <TableCell
                        key={c.key}
                        className={cn(
                          'font-semibold whitespace-nowrap',
                          c.align === 'right' && 'text-right tabular-nums',
                          c.mono && 'font-mono text-xs',
                        )}
                      >
                        {answer.table!.totalRow![c.key] ?? ''}
                      </TableCell>
                    ))}
                  </TableRow>
                </TableFooter>
              )}
            </Table>
          </div>
          <div className="flex flex-wrap items-center justify-between gap-2 border-t border-border bg-muted/30 px-3 py-2">
            <p className="text-xs text-muted-foreground">
              {answer.table.note ?? `${answer.table.rows.length} rows returned from authorised records.`}
            </p>
            {answer.table.link && (
              <Button asChild variant="outline" size="xs">
                <Link to={answer.table.link.to}>
                  {answer.table.link.label}
                  <ArrowUpRightIcon className="size-3" aria-hidden="true" />
                </Link>
              </Button>
            )}
          </div>
        </div>
      )}

      {/* Citations */}
      <div className="flex flex-wrap items-center gap-1.5">
        <span className="inline-flex items-center gap-1.5 text-xs text-muted-foreground">
          <DatabaseIcon className="size-3.5" aria-hidden="true" />
          Derived from
        </span>
        {answer.sources.map((s) => (
          <Badge key={s.label} variant="secondary" className="gap-1 font-normal">
            <span className="font-mono tabular-nums">{formatNumber(s.count)}</span>
            {s.label.toLowerCase()}
          </Badge>
        ))}
        <Badge variant="outline" className="gap-1 font-normal">
          <span className="font-mono tabular-nums">{answer.confidence}%</span> match confidence
        </Badge>
      </div>

      {/* Show working */}
      <Collapsible open={workingOpen} onOpenChange={setWorkingOpen}>
        <CollapsibleTrigger asChild>
          <Button variant="ghost" size="sm" className="-ml-2 h-8 gap-1.5 text-xs">
            <SigmaIcon className="size-3.5" aria-hidden="true" />
            {workingOpen ? 'Hide working' : 'Show working'}
            <ChevronDownIcon
              className={cn('size-3.5 transition-transform', workingOpen && 'rotate-180')}
              aria-hidden="true"
            />
          </Button>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className="mt-1 rounded-lg border border-dashed border-border bg-muted/30 px-4 py-3">
            <p className="mb-2 text-xs font-medium text-foreground">How this answer was derived</p>
            <ol className="space-y-1.5">
              {answer.working.map((w, i) => (
                <li key={i} className="flex gap-2.5 text-xs leading-relaxed text-muted-foreground">
                  <span className="mt-px shrink-0 font-mono text-[10px] text-primary">{String(i + 1).padStart(2, '0')}</span>
                  <span>{w}</span>
                </li>
              ))}
            </ol>
          </div>
        </CollapsibleContent>
      </Collapsible>

      {/* Message actions */}
      <div className="flex flex-wrap items-center gap-1">
        <Button variant="ghost" size="xs" onClick={handleCopy} className="gap-1.5 text-muted-foreground">
          {copied ? <CheckIcon className="size-3.5" aria-hidden="true" /> : <CopyIcon className="size-3.5" aria-hidden="true" />}
          {copied ? 'Copied' : 'Copy'}
        </Button>
        <Button variant="ghost" size="xs" onClick={onRegenerate} className="gap-1.5 text-muted-foreground">
          <RefreshCwIcon className="size-3.5" aria-hidden="true" />
          Regenerate
        </Button>
        {answer.table && answer.table.rows.length > 0 && (
          <Button variant="ghost" size="xs" onClick={handleExport} className="gap-1.5 text-muted-foreground">
            <DownloadIcon className="size-3.5" aria-hidden="true" />
            Export CSV
          </Button>
        )}
        <span className="mx-1 h-4 w-px bg-border" aria-hidden="true" />
        <Button
          variant="ghost"
          size="icon-xs"
          onClick={() => handleVote('up')}
          aria-label="Helpful answer"
          className={cn('text-muted-foreground', vote === 'up' && TONE_TEXT_CLASSES.positive)}
        >
          <ThumbsUpIcon className="size-3.5" aria-hidden="true" />
        </Button>
        <Button
          variant="ghost"
          size="icon-xs"
          onClick={() => handleVote('down')}
          aria-label="Unhelpful answer"
          className={cn('text-muted-foreground', vote === 'down' && TONE_TEXT_CLASSES.critical)}
        >
          <ThumbsDownIcon className="size-3.5" aria-hidden="true" />
        </Button>
      </div>

      {/* Follow-ups */}
      {answer.followUps.length > 0 && (
        <div className="flex flex-wrap items-center gap-1.5 border-t border-border pt-3">
          <span className="text-xs text-muted-foreground">Ask next</span>
          {answer.followUps.map((f) => (
            <Button
              key={f}
              variant="outline"
              size="xs"
              onClick={() => onFollowUp(f)}
              className="h-auto min-h-7 rounded-full py-1 text-left font-normal whitespace-normal"
            >
              {f}
            </Button>
          ))}
        </div>
      )}
    </div>
  )
}
